version: '3.9'

services:
  backend:
    container_name: shift-management-system
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3005:3000"
    env_file:
      - .env
    restart: "unless-stopped"
    volumes:
      - .:/rails
  postgres:
      container_name: shift-management-app-db
      image: postgres:13.3-alpine
      restart: "unless-stopped"
      env_file:
        - .env
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - 5435:5432
      environment:
        - POSTGRES_USER=platform_user
        - POSTGRES_PASSWORD=local_db_platform
        - POSTGRES_DB=shift-management-app-db
        
volumes:
  postgres_data:
    driver: local