version: '3.9'

services:
  backend:
    container_name: employee-management-system
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3005:3000"
    env_file:
      - .env
    restart: "unless-stopped"
    volumes:
      - .:/rails
    networks:
      - employee-management-network
    depends_on:
      - postgres

  postgres:
      container_name: employee-management-app-db
      image: postgres:13.3-alpine
      restart: "unless-stopped"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - 5435:5432
      environment:
        - POSTGRES_USER=platform_user
        - POSTGRES_PASSWORD=local_db_platform
        - POSTGRES_DB=employee-management-app-db
      networks:
            - employee-management-network
        
volumes:
  postgres_data:
    driver: local

networks:
  employee-management-network:
    driver: bridge