version: '3.9'

services:
  backend-test:
    container_name: employee-management-system-test
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3006:3000"
    volumes:
      - .:/rails
    networks:
      - employee-management-network-test
    depends_on:
      - postgres-test

  postgres-test:
    container_name: employee-management-app-db-test
    image: postgres:13.3-alpine
    restart: "unless-stopped"
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=platform_user_test
      - POSTGRES_PASSWORD=test_db_platform
      - POSTGRES_DB=employee-management-app-db-test
    networks:
      - employee-management-network-test

networks:
  employee-management-network-test:
    driver: bridge