# PostgreSQL configuration for Rails

# This configuration is for a Rails application that uses PostgreSQL as its database.

# The configuration is read from the environment variables POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB, and RAILS_MAX_THREADS.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DATABASE_NAME'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
  port: <%= ENV['PRODUCTION_DATABASE_PORT'] %>
  host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>

staging:
  <<: *default
  database: <%= ENV['STAGING_DATABASE_NAME'] %>
  username: <%= ENV['STAGING_DATABASE_USERNAME'] %>
  password: <%= ENV['STAGING_DATABASE_PASSWORD'] %>
  port: <%= ENV['STAGING_DATABASE_PORT'] %>
  host: <%= ENV['STAGING_DATABASE_HOST'] %>
  

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  host: <%= ENV['DATABASE_HOST'] %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: sqlite3
  database: ":memory:"
  pool: 5
  timeout: 5000

