name: CI

on:
  pull_request:
  push:
    branches: [ main ]
  paths:
      - 'backend-api/**'
      - ".github/workflows/ci.yml"


jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: |
          cd backend-api 
          bin/brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: |
          cd backend-api 
          bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: |
          cd backend-api
          echo "Running Rubocop"
          bundle exec rubocop -a
          echo "Rubocop auto-correction applied"

      - name: Commit formatted changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "automated code fixes and formatting by rubocop"

  test:
    needs: [scan_ruby, scan_js, lint]
    uses: ./.github/workflows/test.yml
